openapi: 3.1.0
info:
  title: Meijun-takeout
  description: Meijun-takeout接口规范
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/v1/'
paths:
    /order/create:
      post:
        summary: 创建订单
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    /store/list:
      get:
        summary: 获取店铺列表
        responses:
          '200':
            description: 成功获取店铺列表
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Store'
    /auth/login:
      post:
          summary: 用户登录
          requestBody:
            content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/AuthLoginDTO'
    /auth/register:
      post:
        summary: 用户注册
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    /user/login:
      post:
        summary: C端用户登录
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginDTO'

components:
  schemas:
    AuthLoginDTO:
      type: object
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
        code:
          type: string
          description: 验证码
        identity:
          type: string
          description: 用户身份
          enum:
            - customer
            - admin
      required:
        - username
        - password
        - code
        - identity
    Admin:
      type: object
      properties:
          id:
            type: integer
            description: 管理员ID
          name:
            type: string
            description: 管理员名称
          password:
            type: string
            description: 管理员密码
      required:
        - name
        - password
    Customer:
      type: object
      properties:
          id:
            type: integer
            description: 用户ID
          name:
            type: string
            description: 用户名称
          password:
            type: string
            description: 用户密码
      required:
        - name
        - password
    UserLoginDTO:
      type: object
      properties:
        code:
          type: string
          description: 微信登录成功后返回的临时登录凭证code
    Order:
      type: object
      properties:
        id:
          type: integer
          description: 订单ID
        customerId:
          type: integer
          description: 用户ID
        storeId:
          type: integer
          description: 店铺ID
        status:
          type: string
          description: 订单状态
          enum:
            - pending
            - processing
            - completed
            - cancelled
      required:
        - customerId
        - storeId
        - status
    Store:
      type: object
      properties:
        id:
          type: integer
          description: 店铺ID
        name:
          type: string
          description: 店铺名称
        address:
          type: string
          description: 店铺地址
      required:
        - name
        - address