spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc::mysql://localhost:3306/mo-db
    username: root
    password: password
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis:
  mapper-locations: classpath:mapper/*.xml
# mo项目配置
mo:
  jwt:
    admin-secret-key: ADMIN-SECRET-KEY
    admin-ttl: 3600000
    admin-token-name: adminToken
    customer-secret-key: CUSTOMER-SECRET-KEY
    customer-ttl: 3600000
    customer-token-name: customerToken
    merchant-secret-key: MERCHANT-SECRET-KEY
    merchant-ttl: 3600000
    merchant-token-name: merchantToken
    employee-secret-key: EMPLOYEE-SECRET-KEY
    employee-ttl: 3600000
    employee-token-name: employeeToken